export const REPEAT_HORIZON_DAYS = 120;

export const initialTasks = [
  {
    id: 1,
    title: "Finish React Project",
    category: "Work",
    date: "2026-08-05",
    completed: false,
    projectId: null,
    description: "",
    steps: [],
    completedAt: null,
    order: 0,
    repeat: "none",
    repeatGroupId: null,
    attachments: [],
  },
  {
    id: 2,
    title: "Buy groceries",
    category: "Personal",
    date: "2026-08-05",
    completed: false,
    projectId: null,
    description: "",
    steps: [],
    completedAt: null,
    order: 1,
    repeat: "none",
    repeatGroupId: null,
    attachments: [],
  },
  {
    id: 3,
    title: "Read 30 pages of a book",
    category: "Self Development",
    date: "2026-08-05",
    completed: false,
    projectId: null,
    description: "",
    steps: [],
    completedAt: null,
    order: 2,
    repeat: "none",
    repeatGroupId: null,
    attachments: [],
  },
  {
    id: 4,
    title: "Go to the gym",
    category: "Health",
    date: "2026-08-05",
    completed: true,
    projectId: null,
    description: "",
    steps: [],
    completedAt: null,
    order: 3,
    repeat: "none",
    repeatGroupId: null,
    attachments: [],
  },
  {
    id: 5,
    title: "Call mom",
    category: "Personal",
    date: "2026-08-06",
    completed: false,
    projectId: null,
    description: "",
    steps: [],
    completedAt: null,
    order: 4,
    repeat: "none",
    repeatGroupId: null,
    attachments: [],
  },
];
export const initialRoutines = [
  {
    id: 1,
    title: "water",
  },
  {
    id: 2,
    title: "Read",
  },
  {
    id: 3,
    title: "Exercise",
  },
];

export const initialProjects = [
  {
    id: 1,
    name: "ToDoApp",
  },
  {
    id: 2,
    name: "Portfolio",
  },
];