export const strings = {
  tr: {
    dashboard: "Dashboard",
    today: "Today",
    dailyRoutine: "Daily Routine",
    calendar: "Calendar",
    archive: "Archive",
    projects: "Projects",
    settings: "Settings",
    settingsTitle: "Ayarlar",
    settingsDescription: "Temayı ve dili buradan yönetebilirsin.",
    themeLabel: "Tema",
    languageLabel: "Dil",
    fontLabel: "Font",

    searchPlaceholder: "Görev ara...",
    todaysTasksTitle: "Bugünün Görevleri",
    filterAll: "Tümü",
    filterActive: "Aktif",
    filterCompleted: "Tamamlanan",
    newTaskPlaceholder: "Yeni görev ekle...",
    addButton: "Ekle",
    deleteButton: "Sil",
    closeButton: "Kapat",
    cancelButton: "İptal",
    categoryWork: "İş",
    categoryPersonal: "Kişisel",
    categorySelfDevelopment: "Kişisel Gelişim",
    categoryOther: "Diğer",
    emptyTaskTitle: "Henüz görev yok",
    emptyTaskSubtitle: "Yeni bir görev ekleyerek başla.",
    emptyTaskMessage: "Görev bulunamadı.",
    completedSection: "Tamamlandı",

    archivePageTitle: "Arşiv",
    archivePageDescription:
      "Bugüne kadar eklenmiş ve silinmemiş tüm görevler burada listelenir.",
    statusAll: "Tüm Durumlar",
    statusActive: "Devam Eden",
    statusCompleted: "Tamamlanan",
    clearFilters: "Temizle",

    projectsPageTitle: "Projeler",
    projectsPageDescription:
      "Projelerine özel görev klasörleri oluşturabilirsin.",
    newProjectPlaceholder: "Yeni proje adı...",
    addProjectButton: "Proje Ekle",
    backToProjects: "← Projelere Dön",
    newProjectTaskPlaceholder: "Proje görevi ekle...",
    addProjectTaskButton: "Görev Ekle",
    taskCountSuffix: "görev",

    greeting: "Merhaba",
    statToday: "Bugünkü Görevler",
    statCompleted: "Tamamlanan",
    statInProgress: "Kalan",
    statOverdue: "Geciken",
    todayStatusChart: "Bugünkü Görev Durumu",
    completedLegend: "Tamamlanan",
    pendingLegend: "Bekleyen",
    completedOfTotal: "tamamlandı",
    weeklyProductivity: "Haftalık Productivity",
    routineTooltipSuffix: "rutin",

    addTaskToDay: "Bu güne görev ekle",
    taskTitlePlaceholder: "Görev başlığı...",

    routineColumnHeader: "Rutin",
    newRoutinePlaceholder: "Yeni rutin ekle...",
    addRoutineButton: "Rutin Ekle",

    descriptionLabel: "Açıklama",
    descriptionPlaceholder: "Bu görev hakkında not ekle...",
    repeatLabel: "Tekrar",
    repeatNone: "Tekrarlanmaz",
    repeatDaily: "Her gün",
    repeatWeekly: "Her hafta",
    repeatHint: "Tekrar ayarlamak için önce göreve bir tarih eklemelisin.",
    attachmentsLabel: "Dosyalar",
    stepsLabel: "Adımlar",
    newStepPlaceholder: "Yeni adım ekle...",
  },
  en: {
    dashboard: "Dashboard",
    today: "Today",
    dailyRoutine: "Daily Routine",
    calendar: "Calendar",
    archive: "Archive",
    projects: "Projects",
    settings: "Settings",
    settingsTitle: "Settings",
    settingsDescription: "Manage your theme and language here.",
    themeLabel: "Theme",
    languageLabel: "Language",
    fontLabel: "Font",

    searchPlaceholder: "Search tasks...",
    todaysTasksTitle: "Today's Tasks",
    filterAll: "All",
    filterActive: "Active",
    filterCompleted: "Completed",
    newTaskPlaceholder: "Add a new task...",
    addButton: "Add",
    deleteButton: "Delete",
    closeButton: "Close",
    cancelButton: "Cancel",
    categoryWork: "Work",
    categoryPersonal: "Personal",
    categorySelfDevelopment: "Self Development",
    categoryOther: "Other",
    emptyTaskTitle: "No tasks yet",
    emptyTaskSubtitle: "Add a new task to get started.",
    emptyTaskMessage: "No tasks found.",
    completedSection: "Completed",

    archivePageTitle: "Archive",
    archivePageDescription:
      "Every task you've added so far, unless deleted, is listed here.",
    statusAll: "All Statuses",
    statusActive: "Active",
    statusCompleted: "Completed",
    clearFilters: "Clear",

    projectsPageTitle: "Projects",
    projectsPageDescription: "Create dedicated task folders for your projects.",
    newProjectPlaceholder: "New project name...",
    addProjectButton: "Add Project",
    backToProjects: "← Back to Projects",
    newProjectTaskPlaceholder: "Add a project task...",
    addProjectTaskButton: "Add Task",
    taskCountSuffix: "tasks",

    greeting: "Hello",
    statToday: "Today's Tasks",
    statCompleted: "Completed",
    statInProgress: "In Progress",
    statOverdue: "Overdue",
    todayStatusChart: "Today's Task Status",
    completedLegend: "Completed",
    pendingLegend: "Pending",
    completedOfTotal: "completed",
    weeklyProductivity: "Weekly Productivity",
    routineTooltipSuffix: "routines",

    addTaskToDay: "Add task to this day",
    taskTitlePlaceholder: "Task title...",

    routineColumnHeader: "Routine",
    newRoutinePlaceholder: "Add a new routine...",
    addRoutineButton: "Add Routine",

    descriptionLabel: "Description",
    descriptionPlaceholder: "Add a note about this task...",
    repeatLabel: "Repeat",
    repeatNone: "Doesn't repeat",
    repeatDaily: "Daily",
    repeatWeekly: "Weekly",
    repeatHint: "Add a date to this task before setting a repeat.",
    attachmentsLabel: "Attachments",
    stepsLabel: "Steps",
    newStepPlaceholder: "Add a new step...",
  },
};