export const strings = {
  tr: {
    dashboard: "Panel",
    today: "Bugün",
    dailyRoutine: "Günlük Rutin",
    calendar: "Takvim",
    archive: "Arşiv",
    projects: "Projeler",
    settings: "Ayarlar",
    settingsTitle: "Ayarlar",
    settingsDescription: "Temayı ve dili buradan yönetebilirsin.",
    themeLabel: "Tema",
    languageLabel: "Dil",
    fontLabel: "Font",
    weekStartLabel: "Haftanın Başlangıcı",
    weekStartMonday: "Pazartesi",
    weekStartSunday: "Pazar",
    greetingMorning: "Günaydın",
    greetingAfternoon: "İyi günler",
    greetingEvening: "İyi akşamlar",
    editTitleHint: "Değiştirmek için çift tıkla",
    dateLabel: "Tarih",
    removeDateButton: "Tarihi kaldır",
    repeatDailyHint: "Her gün tekrarlanır",
    repeatWeeklyHint: "Her hafta tekrarlanır",
    previousLabel: "Önceki",
    nextLabel: "Sonraki",

    searchPlaceholder: "Görev ara...",
    todaysTasksTitle: "Bugünün Görevleri",
    filterAll: "Tümü",
    filterActive: "Aktif",
    filterCompleted: "Tamamlanan",
    newTaskPlaceholder: "Yeni görev ekle...",
    addButton: "Ekle",
    deleteButton: "Sil",
    closeButton: "Kapat",
    cancelButton: "İptal",
    categoryWork: "İş",
    categoryPersonal: "Kişisel",
    categorySelfDevelopment: "Kişisel Gelişim",
    categoryOther: "Diğer",
    emptyTaskTitle: "Henüz görev yok",
    emptyTaskSubtitle: "Yeni bir görev ekleyerek başla.",
    emptyTaskMessage: "Görev bulunamadı.",
    completedSection: "Tamamlandı",

    archivePageTitle: "Arşiv",
    archivePageDescription:
      "Bugüne kadar eklenmiş ve silinmemiş tüm görevler burada listelenir.",
    statusAll: "Tüm Durumlar",
    statusActive: "Devam Eden",
    statusCompleted: "Tamamlanan",
    clearFilters: "Temizle",

    projectsPageTitle: "Projeler",
    projectsPageDescription:
      "Projelerine özel görev klasörleri oluşturabilirsin.",
    newProjectPlaceholder: "Yeni proje adı...",
    addProjectButton: "Proje Ekle",
    backToProjects: "← Projelere Dön",
    newProjectTaskPlaceholder: "Proje görevi ekle...",
    addProjectTaskButton: "Görev Ekle",
    taskCountSuffix: "görev",

    greeting: "Merhaba",
    dashboardQuotes: [
      "Mükemmellik değil, ilerleme önemli.",
      "Bir seferde bir görev, yeter.",
      "Süreklilik, yoğunluktan daha güçlüdür.",
      "Küçük adımlar da seni ileri taşır.",
      "Bugün yepyeni bir başlangıç.",
      "Yapılmış, mükemmelden iyidir.",
      "Attığın her onay işareti değerlidir.",
      "Her adımla ivme kazanırsın.",
      "Bugüne odaklan, sürece güven.",
      "Mükemmel olmana gerek yok, sadece düzenli ol.",
    ],
    yesterdayCompletedMessage: (count) => `Dün ${count} görev tamamladın.`,
    weekCompletedMessage: (count) => `Bu hafta ${count} görev tamamladın.`,
    routineStreakMessage: (routineName, days) =>
      `${routineName} rutinini ${days} gündür aksatmıyorsun.`,

    statToday: "Bugünkü Görevler",
    statCompleted: "Tamamlanan",
    statInProgress: "Kalan",
    statOverdue: "Geciken",
    todayStatusChart: "Bugünkü Görev Durumu",
    completedLegend: "Tamamlanan",
    pendingLegend: "Bekleyen",
    completedOfTotal: "tamamlandı",
    weeklyProductivity: "Haftalık Verimlilik",
    routineTooltipSuffix: "rutin",

    addTaskToDay: "Bu güne görev ekle",
    taskTitlePlaceholder: "Görev başlığı...",

    routineColumnHeader: "Rutin",
    newRoutinePlaceholder: "Yeni rutin ekle...",
    addRoutineButton: "Rutin Ekle",

    descriptionLabel: "Açıklama",
    descriptionPlaceholder: "Bu görev hakkında not ekle...",
    repeatLabel: "Tekrar",
    repeatNone: "Tekrarlanmaz",
    repeatDaily: "Her gün",
    repeatWeekly: "Her hafta",
    repeatHint: "Tekrar ayarlamak için önce göreve bir tarih eklemelisin.",
    attachmentsLabel: "Dosyalar",
    stepsLabel: "Adımlar",
    newStepPlaceholder: "Yeni adım ekle...",
    project: "Proje",
    noProject: "Proje yok",
    deleteButtonAria: "Görevi sil",
    confirmDeleteMessage: (title) =>
      `"${title}" görevini silmek istediğine emin misin? Bu işlem geri alınamaz.`,
    confirmDeleteCancel: "Vazgeç",
    confirmDeleteConfirm: "Evet, Sil",
    fileTooLargeWarning:
      "Bu dosya çok büyük (1MB üzeri). Tarayıcı depolama alanı sınırlı olduğu için daha küçük bir dosya seçmelisin.",
    deleteStepAria: "Adımı sil",
  },
  en: {
    dashboard: "Dashboard",
    today: "Today",
    dailyRoutine: "Daily Routine",
    calendar: "Calendar",
    archive: "Archive",
    projects: "Projects",
    settings: "Settings",
    settingsTitle: "Settings",
    settingsDescription: "Manage your theme and language here.",
    themeLabel: "Theme",
    languageLabel: "Language",
    fontLabel: "Font",
    weekStartLabel: "Week Starts On",
    weekStartMonday: "Monday",
    weekStartSunday: "Sunday",
    greetingMorning: "Good morning",
    greetingAfternoon: "Good afternoon",
    greetingEvening: "Good evening",
    editTitleHint: "Double-click to edit",
    dateLabel: "Date",
    removeDateButton: "Remove date",
    repeatDailyHint: "Repeats daily",
    repeatWeeklyHint: "Repeats weekly",
    previousLabel: "Previous",
    nextLabel: "Next",

    searchPlaceholder: "Search tasks...",
    todaysTasksTitle: "Today's Tasks",
    filterAll: "All",
    filterActive: "Active",
    filterCompleted: "Completed",
    newTaskPlaceholder: "Add a new task...",
    addButton: "Add",
    deleteButton: "Delete",
    closeButton: "Close",
    cancelButton: "Cancel",
    categoryWork: "Work",
    categoryPersonal: "Personal",
    categorySelfDevelopment: "Self Development",
    categoryOther: "Other",
    emptyTaskTitle: "No tasks yet",
    emptyTaskSubtitle: "Add a new task to get started.",
    emptyTaskMessage: "No tasks found.",
    completedSection: "Completed",

    archivePageTitle: "Archive",
    archivePageDescription:
      "Every task you've added so far, unless deleted, is listed here.",
    statusAll: "All Statuses",
    statusActive: "Active",
    statusCompleted: "Completed",
    clearFilters: "Clear",

    projectsPageTitle: "Projects",
    projectsPageDescription: "Create dedicated task folders for your projects.",
    newProjectPlaceholder: "New project name...",
    addProjectButton: "Add Project",
    backToProjects: "← Back to Projects",
    newProjectTaskPlaceholder: "Add a project task...",
    addProjectTaskButton: "Add Task",
    taskCountSuffix: "tasks",

    greeting: "Hello",
    dashboardQuotes: [
      "Progress, not perfection.",
      "One task at a time.",
      "Consistency beats intensity.",
      "Small steps still move you forward.",
      "Today is a fresh start.",
      "Done is better than perfect.",
      "Every checkbox counts.",
      "Momentum builds with every step.",
      "Focus on today, trust the process.",
      "You don't have to be perfect, just consistent.",
    ],
    yesterdayCompletedMessage: (count) =>
      `You completed ${count} task${count !== 1 ? "s" : ""} yesterday.`,
    weekCompletedMessage: (count) =>
      `You've completed ${count} task${count !== 1 ? "s" : ""} this week.`,
    routineStreakMessage: (routineName, days) =>
      `You've kept up ${routineName} for ${days} days.`,

    statToday: "Today's Tasks",
    statCompleted: "Completed",
    statInProgress: "In Progress",
    statOverdue: "Overdue",
    todayStatusChart: "Today's Task Status",
    completedLegend: "Completed",
    pendingLegend: "Pending",
    completedOfTotal: "completed",
    weeklyProductivity: "Weekly Productivity",
    routineTooltipSuffix: "routines",

    addTaskToDay: "Add task to this day",
    taskTitlePlaceholder: "Task title...",

    routineColumnHeader: "Routine",
    newRoutinePlaceholder: "Add a new routine...",
    addRoutineButton: "Add Routine",

    descriptionLabel: "Description",
    descriptionPlaceholder: "Add a note about this task...",
    repeatLabel: "Repeat",
    repeatNone: "Doesn't repeat",
    repeatDaily: "Daily",
    repeatWeekly: "Weekly",
    repeatHint: "Add a date to this task before setting a repeat.",
    attachmentsLabel: "Attachments",
    stepsLabel: "Steps",
    newStepPlaceholder: "Add a new step...",
    project: "Project",
    noProject: "No project",
    deleteButtonAria: "Delete task",
    confirmDeleteMessage: (title) =>
      `Are you sure you want to delete "${title}"? This action cannot be undone.`,
    confirmDeleteCancel: "Cancel",
    confirmDeleteConfirm: "Yes, Delete",
    fileTooLargeWarning:
      "This file is too large (over 1MB). Since browser storage is limited, please choose a smaller file.",
    deleteStepAria: "Delete step",
  },
};
export const pageTitleKeyMap = {
  Dashboard: "dashboard",
  Today: "today",
  "Daily Routine": "dailyRoutine",
  Calendar: "calendar",
  Archive: "archive",
  Projects: "projects",
  Settings: "settings",
};
